### ISSUE TITLE
Windows binary

### ISSUE THREAD

**Issue by OverPaw** [sz3/libcimbar#51]
Is there any way to build an executable of encoder for Windows 7?
What tools are needed and is there any instruction?

**Comment by sz3** [comment]
The easiest way to run the encoder on windows right now is to download the asm.js encoder (https://github.com/sz3/libcimbar/releases/download/v0.5.5/cimbar.asmjs.zip), extract it, and open `index.html` in the browser. You could also run the wasm version on a local webserver.

****

But as for windows builds specifically...

I haven't done a windows build of libcimbar. There's no reason it *can't* build on win7, but I imagine it's going to take some work.

The basic shape of the problem is:
* the OpenCV windows libraries are built with Visual Studio
* libcimbar will need some amount of changes to work with the VS compiler and linker

But if you or anyone else is up for a challenge, I'm not going to stop you. :smiley:

**Comment by OverPaw** [comment]
> The easiest way to run the encoder on windows right now is to download the asm.js encoder (https://github.com/sz3/libcimbar/releases/download/v0.5.5/cimbar.asmjs.zip), extract it, and open `index.html` in the browser. You could also run the wasm version on a local webserver.

Thank you. This solution is good enough. I didn't know that web-version can work offline.
